# Generated by Django 5.2b1 on 2025-03-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visibleMinority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Neighbourhood', models.CharField(max_length=200, unique=True)),
                ('NeighbourhoodId', models.IntegerField()),
                ('Black', models.IntegerField()),
                ('Chinese', models.IntegerField()),
                ('SouthAsian', models.IntegerField()),
                ('Filipino', models.IntegerField()),
                ('LatinAmerican', models.IntegerField()),
                ('SoutheastAsian', models.IntegerField()),
                ('Arab', models.IntegerField()),
                ('WestAsian', models.IntegerField()),
                ('Korean', models.IntegerField()),
                ('Japanese', models.IntegerField()),
            ],
        ),
    ]
