# Generated by Django 5.2b1 on 2025-03-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Welcome_Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nativeLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Neighbourhood', models.CharField(max_length=200, unique=True)),
                ('NeighbourhoodId', models.IntegerField()),
                ('Language_French', models.IntegerField()),
                ('Language_Chinese', models.IntegerField()),
                ('Language_Tamil', models.IntegerField()),
                ('Language_Italian', models.IntegerField()),
                ('Language_Spanish', models.IntegerField()),
                ('Language_Portuguese', models.IntegerField()),
                ('Language_Tagalog', models.IntegerField()),
                ('Language_Urdu', models.IntegerField()),
                ('Language_Russian', models.IntegerField()),
                ('Language_Farsi', models.IntegerField()),
                ('Language_Korean', models.IntegerField()),
            ],
        ),
    ]
