# Generated by Django 5.1.6 on 2025-03-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Welcome_Home', '0002_agedensity_civics_equity_economics_nativelanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Neighbourhood', models.CharField(max_length=200, unique=True)),
                ('NeighbourhoodId', models.IntegerField()),
                ('Green_rebate_programs', models.IntegerField()),
                ('Green_spaces', models.IntegerField()),
                ('pollutant_carcinogenic_score', models.IntegerField()),
                ('pollutant_noncarcinogenic_score', models.IntegerField()),
                ('pollutant_release', models.IntegerField()),
                ('tree_cover', models.IntegerField()),
            ],
        )

    ]
